// Export all GraphQL queries from a central location
export {
  OVERVIEW_QUERY,
  OVERVIEW_CARDS_QUERY,
  OVERVIEW_VIOLATIONS_QUERY,
  OVERVIEW_EVALUATIONS_QUERY,
  OVERVIEW_TRENDS_QUERY,
  OVERVIEW_SUBSCRIPTION,
  OVERVIEW_VIOLATIONS_SUBSCRIPTION,
  OVERVIEW_EVALUATIONS_SUBSCRIPTION
} from './overview';

export {
  POLICIES_QUERY,
  POLICY_QUERY,
  POLICIES_STATS_QUERY,
  POLICY_VIOLATIONS_QUERY
} from './policies';

export {
  VIOLATIONS_QUERY,
  VIOLATION_QUERY,
  VIOLATIONS_STATS_QUERY,
  VIOLATIONS_TRENDS_QUERY
} from './violations';

export {
  RESOURCES_QUERY,
  RESOURCE_QUERY,
  RESOURCES_STATS_QUERY,
  RESOURCES_COMPLIANCE_QUERY
} from './resources';

export {
  EVALUATIONS_QUERY,
  EVALUATION_QUERY,
  EVALUATIONS_STATS_QUERY,
  EVALUATION_RESULTS_QUERY
} from './evaluations';

export {
  ATTACK_PATHS_QUERY,
  ATTACK_PATH_QUERY,
  ATTACK_PATHS_ANALYSIS_QUERY
} from './attackPaths';

export {
  COMPLIANCE_REPORT_QUERY,
  COMPLIANCE_FRAMEWORKS_QUERY,
  COMPLIANCE_CONTROLS_QUERY,
  COMPLIANCE_TRENDS_QUERY
} from './compliance';

export {
  ML_MODELS_QUERY,
  ML_MODEL_QUERY,
  ML_TRAINING_JOBS_QUERY,
  ML_PERFORMANCE_QUERY,
  ML_DRIFT_QUERY
} from './ml';

export {
  USERS_QUERY,
  USER_QUERY,
  ACCOUNTS_QUERY,
  ACCOUNT_QUERY,
  TENANTS_QUERY,
  TENANT_QUERY
} from './accounts';

export {
  ALERTS_QUERY,
  ALERT_QUERY,
  ALERTS_STATS_QUERY,
  NOTIFICATIONS_QUERY
} from './alerts';

export {
  ANALYTICS_QUERY,
  ANALYTICS_VIOLATIONS_QUERY,
  ANALYTICS_RESOURCES_QUERY,
  ANALYTICS_COSTS_QUERY,
  ANALYTICS_PERFORMANCE_QUERY
} from './analytics';
